name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/*  # Adjust as needed for feature branch patterns

jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          make create-environment
          source venv/bin/activate
          make requirements

      # Uncomment to set up PostgreSQL later in the project
      # - name: Set up PostgreSQL
      #   uses: hyness/postgresql-action@v2
      #   with:
      #       postgresql version: '13'
      #       postgresql db: 'test_db'
      #       postgresql user: 'test_user'
      #       postgresql password: 'test_password'

      - name: Run Tests and Checks
        env:
          AWS_ACCESS_KEY_ID: ${{ github.ref == 'refs/heads/main' && secrets.AWS_ACCESS_KEY_ID || 'test' }}
          AWS_SECRET_ACCESS_KEY: ${{ github.ref == 'refs/heads/main' && secrets.AWS_SECRET_ACCESS_KEY || 'test' }}
          # Uncomment for test database later in the project
          # DATABASE_URL: ${{ github.ref == 'refs/heads/main' && secrets.REAL_DATABASE_URL || 'postgresql://test_user:test_password@localhost:5432/test_db' }}
        run: |
          make run-checks

  deploy-lambda:
    name: deploy-lambda
    runs-on: ubuntu-latest
    needs: run-tests
    if: github.ref == 'refs/heads/main'  # Only runs for the main branch
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Lambda Layer Packaging
        run: |
          rm -rf layer/python
          mkdir -p layer/python
          pip install -r layer_requirements.txt -t layer/python/
          cd extract_layer && zip -r ../layer.zip ./*

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan

      - name: Upload Lambda Layer to S3
        run: |
          aws s3 cp layer.zip s3://under-the-clouds-code/layer_code.zip 
        # needs actual bucket name

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
